name: Test
on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
      - feature/**
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.13"
          - "1.19"
          - "1.20"
          - "1.21"
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build & Test
      run: |
        go test -race ./...
